# -*- mode: ruby -*-
# vi: set ft=ruby :

# global
BOX = "sbeliakou/centos"
server_ip="192.168.56.11"
agent_ip="192.168.56.33"


Vagrant.configure("2") do |config|
  config.vm.box = BOX

  # main machine 
  config.vm.define "shvedau_zabbix_server1" do |zabbix1|
    zabbix1.vm.network "private_network", ip: server_ip
    zabbix1.vm.hostname = "zabbix-main"

    zabbix1.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.name = "shvedau_zabbix1_vm"
    end

    zabbix1.vm.provision "file", source: "./variables.conf", destination: "/tmp/vars"
    zabbix1.vm.provision "shell", path: "shvedau_zabbix_server_setup.sh"
  end

  # second machine
  config.vm.define "shvedau_zabbix_server2" do |zabbix2|
    zabbix2.vm.network "private_network", ip: agent_ip
    zabbix2.vm.hostname = "zabbix-agents"

    zabbix2.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.name = "shvedau_zabbix2_vm"
    end

    zabbix2.vm.provision "file", source: "./variables.conf", destination: "/tmp/vars"
    zabbix2.vm.provision "shell", path: "shvedau_zabbix_agents_setup.sh"
  end
end
    