# -*- mode: ruby -*-
# vi: set ft=ruby :

# global
BOX = "sbeliakou/centos"
server_ip="192.168.56.11"
agent_ip="192.168.56.33"


Vagrant.configure("2") do |config|
  config.vm.box = BOX

  # main machine 
  config.vm.define "shvedau_vm1" do |zabbix1|
    zabbix1.vm.network "private_network", ip: server_ip
    zabbix1.vm.hostname = "vm11"

    zabbix1.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.name = "shvedau_vm1_tomcat"
    end

    # # using dos2unix due to the empty char's in files problems on windows-vagrant-centos setup
    # zabbix1.vm.provision "shell", inline: "sudo yum install -y dos2unix && dos2unix /vagrant/*"
    zabbix1.vm.provision "shell", path: "shvedau_vm1_setup.sh"
  end

  # second machine
  config.vm.define "shvedau_vm2" do |zabbix2|
    zabbix2.vm.network "private_network", ip: agent_ip
    zabbix2.vm.hostname = "vm33"

    zabbix2.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.name = "shvedau_vm2_kibana"
    end

    ## using dos2unix due to the empty char's in files problems on windows-vagrant-centos setup
    # zabbix2.vm.provision "shell", inline: "sudo yum install -y dos2unix && dos2unix /vagrant/*"
    zabbix2.vm.provision "shell", path: "shvedau_vm2_setup.sh"
  end
end
    